INSERT INTO perguntas (questao, correta, falsa1, falsa2, falsa3, dificuldade) VALUES
('Qual é a capital do Brasil?', 'Brasília', 'Rio de Janeiro', 'São Paulo', 'Belo Horizonte', 'FACIL'),
('Quantos continentes existem?', '7', '5', '6', '8', 'FACIL'),
('Qual é a fórmula da água?', 'H2O', 'CO2', 'NaCl', 'CH4', 'FACIL'),
('Em que ano o homem pisou na Lua pela primeira vez?', '1969', '1972', '1959', '1965', 'MEDIA'),
('Qual planeta é conhecido como o planeta vermelho?', 'Marte', 'Júpiter', 'Saturno', 'Netuno', 'FACIL'),
('Quem escreveu Dom Casmurro?', 'Machado de Assis', 'José de Alencar', 'Carlos Drummond', 'Clarice Lispector', 'MEDIA'),
('Qual é a maior floresta tropical do mundo?', 'Amazônica', 'Atlântica', 'Boreal', 'Savana', 'FACIL'),
('Quem pintou a Mona Lisa?', 'Leonardo da Vinci', 'Van Gogh', 'Michelangelo', 'Monet', 'MEDIA'),
('Quanto é 12 x 12?', '144', '122', '132', '124', 'FACIL'),
('Qual o maior animal terrestre?', 'Elefante Africano', 'Rinoceronte', 'Girafa', 'Hipopótamo', 'FACIL'),
('Quem descobriu o Brasil?', 'Pedro Álvares Cabral', 'Vasco da Gama', 'Cristóvão Colombo', 'Dom Pedro I', 'FACIL'),
('Qual é a moeda oficial do Japão?', 'Iene', 'Yuan', 'Won', 'Euro', 'MEDIA'),
('Quem foi o primeiro presidente do Brasil?', 'Deodoro da Fonseca', 'Getúlio Vargas', 'Dom Pedro II', 'Juscelino Kubitschek', 'DIFICIL'),
('Qual é a capital da Argentina?', 'Buenos Aires', 'Santiago', 'Lima', 'Montevidéu', 'FACIL'),
('Quantos lados tem um decágono?', '10', '8', '12', '6', 'MEDIA'),
('O que significa “ONU”?', 'Organização das Nações Unidas', 'Organização Nacional Unificada', 'Ordem Nacional Unida', 'Organismo das Nações Unidas', 'FACIL'),
('Qual o nome do autor de “O Pequeno Príncipe”?', 'Antoine de Saint-Exupéry', 'Victor Hugo', 'Jean-Paul Sartre', 'Albert Camus', 'MEDIA'),
('Quantos segundos tem uma hora?', '3600', '1800', '3000', '6000', 'MEDIA'),
('Qual o símbolo químico do ouro?', 'Au', 'Ag', 'Go', 'Or', 'FACIL'),
('Qual foi a primeira Copa do Mundo?', '1930', '1940', '1922', '1934', 'DIFICIL'),
('Quem foi Albert Einstein?', 'Físico', 'Matemático', 'Astrônomo', 'Filósofo', 'FACIL'),
('Em que estado fica o Pantanal?', 'Mato Grosso do Sul', 'Amazonas', 'Bahia', 'Pará', 'MEDIA'),
('Qual o menor país do mundo?', 'Vaticano', 'Mônaco', 'Luxemburgo', 'Andorra', 'DIFICIL'),
('Quem é o autor de "Romeu e Julieta"?', 'William Shakespeare', 'Jane Austen', 'Charles Dickens', 'Oscar Wilde', 'FACIL'),
('Qual é o nome do satélite natural da Terra?', 'Lua', 'Sol', 'Estrela', 'Marte', 'FACIL'),
('Qual é o maior oceano do planeta?', 'Pacífico', 'Atlântico', 'Índico', 'Ártico', 'FACIL'),
('Qual é o órgão responsável pela produção de insulina?', 'Pâncreas', 'Fígado', 'Rim', 'Estômago', 'MEDIA'),
('Qual a cor da clorofila?', 'Verde', 'Azul', 'Vermelha', 'Amarela', 'FACIL'),
('Quem foi o criador da lâmpada elétrica?', 'Thomas Edison', 'Nikola Tesla', 'Benjamin Franklin', 'Alexander Graham Bell', 'MEDIA'),
('O que é um triângulo escaleno?', 'Tem todos os lados diferentes', 'Tem dois lados iguais', 'Tem todos os ângulos retos', 'Tem lados iguais', 'DIFICIL'),
('O que é um haicai?', 'Poema curto', 'Dança japonesa', 'Pintura tradicional', 'Estilo de caligrafia', 'DIFICIL'),
('Qual o valor de PI (aproximadamente)?', '3.14', '2.71', '1.62', '4.20', 'FACIL'),
('Qual a capital da França?', 'Paris', 'Londres', 'Roma', 'Berlim', 'FACIL'),
('O que é um eclipse solar?', 'Lua entre Sol e Terra', 'Sol entre Lua e Terra', 'Sol atrás da Lua', 'Sol se apaga', 'MEDIA'),
('Quem foi Martin Luther King Jr.?', 'Líder dos direitos civis', 'Presidente americano', 'Ator', 'Cientista', 'MEDIA'),
('Qual desses é um mamífero aquático?', 'Baleia', 'Tubarão', 'Polvo', 'Cavalo-marinho', 'FACIL'),
('Quantos planetas tem o sistema solar?', '8', '7', '9', '6', 'MEDIA'),
('Qual o plural de “cidadão”?', 'Cidadãos', 'Cidadões', 'Cidadães', 'Cidades', 'FACIL'),
('Qual é a capital de Portugal?', 'Lisboa', 'Madrid', 'Barcelona', 'Porto', 'FACIL'),
('Quem foi o primeiro homem no espaço?', 'Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'Laika', 'DIFICIL'),
('Qual o nome do processo de transformação da lagarta em borboleta?', 'Metamorfose', 'Mutação', 'Transformação', 'Evolução', 'FACIL'),
('Em que continente fica a Austrália?', 'Oceania', 'Ásia', 'Europa', 'América', 'MEDIA'),
('Quantos graus tem um ângulo reto?', '90', '45', '180', '60', 'FACIL'),
('Qual é o maior país do mundo em extensão?', 'Rússia', 'China', 'Canadá', 'Estados Unidos', 'FACIL'),
('Qual é o nome do famoso cientista que propôs a teoria da evolução?', 'Charles Darwin', 'Newton', 'Einstein', 'Pasteur', 'MEDIA'),
('Quantas cordas tem um violão tradicional?', '6', '4', '5', '7', 'FACIL'),
('O que significa “IBGE”?', 'Instituto Brasileiro de Geografia e Estatística', 'Instituição Brasileira de Gestão Econômica', 'Instituto de Bancos do Governo Estadual', 'Indicação Brasileira de Geopolítica Econômica', 'MEDIA'),
('Qual a capital do estado de Pernambuco?', 'Recife', 'Natal', 'Fortaleza', 'Maceió', 'FACIL'),
('Quem foi Clarice Lispector?', 'Escritora', 'Atriz', 'Cientista', 'Arquiteta', 'MEDIA'),
('Qual o menor número primo?', '2', '1', '3', '0', 'DIFICIL');
